"""empty message

Revision ID: 04de8761e7b5
Revises: d7e7ae744490
Create Date: 2025-07-10 15:57:43.779136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04de8761e7b5'
down_revision = 'd7e7ae744490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano_nacimiento', sa.String(length=50), nullable=True))
        batch_op.drop_column('año_nacimiento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('año_nacimiento', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('ano_nacimiento')

    # ### end Alembic commands ###
