"""empty message

Revision ID: 72bcc82787fd
Revises: d3c314d98554
Create Date: 2025-07-10 11:30:15.105131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bcc82787fd'
down_revision = 'd3c314d98554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('año_nacimiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('altura',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('color_piel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('color_piel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('altura',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('año_nacimiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
