"""empty message

Revision ID: 96e4a18e03d0
Revises: 04de8761e7b5
Create Date: 2025-07-10 18:46:07.985797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e4a18e03d0'
down_revision = '04de8761e7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
