"""empty message

Revision ID: d3c314d98554
Revises: c538407d685c
Create Date: 2025-07-10 11:21:35.556173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c314d98554'
down_revision = 'c538407d685c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
