"""empty message

Revision ID: d7e7ae744490
Revises: 72bcc82787fd
Create Date: 2025-07-10 12:24:51.426814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e7ae744490'
down_revision = '72bcc82787fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('poblacion',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('diametro',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('diametro',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('poblacion',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
