"""empty message

Revision ID: e7c5d709905c
Revises: fe8f8eb8c5ee
Create Date: 2025-07-11 09:01:42.206463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c5d709905c'
down_revision = 'fe8f8eb8c5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swapi_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swapi_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swapi_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.drop_column('swapi_id')

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.drop_column('swapi_id')

    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.drop_column('swapi_id')

    # ### end Alembic commands ###
